//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionaireEtudiant.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-2O5215P\\SQLEXPRESS;Initial Catalog=projet_wpf;Integrated Secu" +
            "rity=True;Encrypt=False")]
        public string ex1ConnectionString {
            get {
                return ((string)(this["ex1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-2O5215P\\SQLEXPRESS;Initial Catalog=projet_wpf;Integrated Secu" +
            "rity=True;TrustServerCertificate=True")]
        public string projet_wpfConnectionString1 {
            get {
                return ((string)(this["projet_wpfConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SQL1001.site4now.net;Initial Catalog=db_ab1607_projetwpf;User Id=db_a" +
            "b1607_projetwpf_admin;Password=zzZ747C@n3L$4#8")]
        public string projet_wpfConnectionString {
            get {
                return ((string)(this["projet_wpfConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SQL1001.site4now.net;Initial Catalog=db_ab1607_projetwpf;User ID=db_a" +
            "b1607_projetwpf_admin;Password=zzZ747C@n3L$4#8;TrustServerCertificate=True")]
        public string db_ab1607_projetwpfConnectionString {
            get {
                return ((string)(this["db_ab1607_projetwpfConnectionString"]));
            }
        }
    }
}
